definitions:
  requests.CreateUserReply:
    properties:
      email:
        type: string
      user_key:
        type: string
    type: object
  requests.CreateUserRequest:
    properties:
      email:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server for Opinion Tracker Service.
  title: Opinion Tracker Service API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Create a new user with the provided email
      parameters:
      - description: User creation request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/requests.CreateUserReply'
      summary: Create a new user
      tags:
      - users
swagger: "2.0"
